### ISSUE TITLE
Gitkey Error

### ISSUE THREAD

**Issue by Quantaism** [Hash-Studios/Prism#106]
import 'package:Prism/gitkey.dart';
       ^
lib/data/pexels/provider/pexelsWithoutProvider.dart:5:8: Error: Error when reading 'lib/gitkey.dart': Sistem belirtilen dosyayı bulamıyor.

import 'package:Prism/gitkey.dart';

**Comment by codenameakshay** [comment]
Please refer to the contributing guidelines before making any changes, it has all the instructions required for gitkey, as well as other stuff which is required for the application. I will be closing the issue, but if you have any other issues, feel free to reopen this one.
