### ISSUE TITLE
fix fullscreen in notch displays

### ISSUE THREAD

**Issue by LiquidatorCoder** [Hash-Studios/Prism#130]

**Comment by Himanshuranjan30** [comment]
I would like to work on this @LiquidatorCoder

**Comment by LiquidatorCoder** [comment]
@Himanshuranjan30 Thanks for showing interest.
For this issue please add `<item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>`
inside `android/app/src/main/res/values/styles.xml` inside the style tag.

**Comment by Himanshuranjan30** [comment]
@LiquidatorCoder Its done and have posted a PR too
Kindly give it a check

**Comment by LiquidatorCoder** [comment]
Okay will update you soon!

**Comment by LiquidatorCoder** [comment]
fixed in 76c76bb919f31f2b76cb7618cb77ad0de71baa3c
