### ISSUE TITLE
fix double tap download button crash while pro user

### ISSUE THREAD

**Issue by LiquidatorCoder** [Hash-Studios/Prism#134]

**Comment by Himanshuranjan30** [comment]
I would like to work on this, can you tell me exactly the dart file where this issue persists @LiquidatorCoder ?

**Comment by LiquidatorCoder** [comment]
@Himanshuranjan30 The issue is more clear in this [video](https://youtu.be/q0JkhbBjZao).
The main download button widget is [here](https://github.com/Hash-Studios/Prism/blob/master/lib/ui/widgets/menuButton/downloadButton.dart).
What is expected behaviour - 
Whenever the download button is pressed rapidly or twice the app should register the first tap and ignore any successive taps while the wallpaper is downloading.

**Comment by Himanshuranjan30** [comment]
assign me this task, I can fix this @LiquidatorCoder
