### ISSUE TITLE
The method 'call' was called on null.

### ISSUE THREAD

**Issue by DLbury** [Hash-Studios/Prism#231]
I added gitkey.dart and google-services.json as required by Contributing, but when I ran it, it prompted me "The method'call' was called on null". And the app has completed the welcome interface, and the black screen is stuck when entering the home page.

Launching lib/main.dart on MuMu in debug mode...
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        32.4s
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
E/AndroidRuntime(12279): FATAL EXCEPTION: main                          
E/AndroidRuntime(12279): Process: com.netease.nemu_vapi_android.nemu, PID: 12279
E/AndroidRuntime(12279): java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.PACKAGE_REPLACED dat=package:com.hash.prism flg=0x4000010 (has extras) } in com.netease.nemu_vapi_android.service.AppService$2@e0708c7
E/AndroidRuntime(12279):        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:901)
E/AndroidRuntime(12279):        at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(12279):        at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(12279):        at android.os.Looper.loop(Looper.java:148)
E/AndroidRuntime(12279):        at android.app.ActivityThread.main(ActivityThread.java:5606)
E/AndroidRuntime(12279):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12279):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
E/AndroidRuntime(12279):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
E/AndroidRuntime(12279): Caused by: java.lang.IndexOutOfBoundsException: Invalid index 3, size is 3
E/AndroidRuntime(12279):        at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
E/AndroidRuntime(12279):        at java.util.ArrayList.get(ArrayList.java:308)
E/AndroidRuntime(12279):        at com.netease.nemu_vapi_android.worker.LocalAppUtil.updateOnAppReplaced(LocalAppUtil.java:190)
E/AndroidRuntime(12279):        at com.netease.nemu_vapi_android.service.AppService$2.onReceive(AppService.java:313)
E/AndroidRuntime(12279):        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:891)
E/AndroidRuntime(12279):        ... 7 more                              
Installing build/app/outputs/flutter-apk/app.apk...                 7.0s
Waiting for MuMu to report its views...                              7ms
I/OpenGLRenderer(15605): Initialized EGL, version 1.4                   
D/        (15605): HostConnection::get() New Host Connection established 0xabb7fde0, tid 15679 host arch 0
E/EGL_emulation(15605): tid 15679: eglSurfaceAttrib(1103): error 0x3009 (EGL_BAD_MATCH)
W/OpenGLRenderer(15605): Failed to set EGL_SWAP_BEHAVIOR on surface 0xa7a517a0, error=EGL_BAD_MATCH
D/        (15605): HostConnection::get() New Host Connection established 0xb08e0be0, tid 15660 host arch 0
W/art     (15605): Method processed more than once: java.lang.String io.flutter.plugin.common.StringCodec.decodeMessage(java.nio.ByteBuffer)
W/art     (15605): Method processed more than once: java.lang.Object io.flutter.plugin.common.StandardMessageCodec.readValueOfType(byte, java.nio.ByteBuffer)
I/flutter (15605): Box Opened                                           
E/EGL_emulation(15605): tid 15679: eglSurfaceAttrib(1103): error 0x3009 (EGL_BAD_MATCH)
W/OpenGLRenderer(15605): Failed to set EGL_SWAP_BEHAVIOR on surface 0xa7a517a0, error=EGL_BAD_MATCH
Syncing files to device MuMu...                                    784ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on MuMu is available at: http://127.0.0.1:56825/Y-aVL0WZdBU=/
I/flutter (15605): Notch Height = 23.846152534146352
I/flutter (15605): [#1 1872x1170 @ 30Hz]
I/flutter (15605): Started Fetching Values from rc
W/art     (15605): Suspending all threads took: 8.752ms
I/art     (15605): Background sticky concurrent mark sweep GC freed 13723(909KB) AllocSpace objects, 8(240KB) LOS objects, 16% free, 6MB/8MB, paused 9.852ms total 19.314ms
I/flutter (15605): Fetched Values from rc
I/flutter (15605): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (15605): The following NoSuchMethodError was thrown during a scheduler callback:
I/flutter (15605): The method 'call' was called on null.
I/flutter (15605): Receiver: null
I/flutter (15605): Tried calling: call()
I/flutter (15605): When the exception was thrown, this was the stack:
I/flutter (15605): #0      SplashScreen.build.<anonymous closure> (package:flare_splash_screen/flare_splash_screen.dart:132:18)
I/flutter (15605): #1      _FlareLoadingState._finished (package:flare_loading/flare_loading.dart:119:23)
I/flutter (15605): #2      _FlareLoadingState.advance (package:flare_loading/flare_loading.dart:138:11)
I/flutter (15605): #3      FlareActorRenderObject.advance (package:flare_flutter/flare_actor.dart:474:22)
I/flutter (15605): #4      FlareRenderBox._beginFrame (package:flare_flutter/flare_render_box.dart:121:5)
I/flutter (15605): #5      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
I/flutter (15605): #6      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1031:11)
I/flutter (15605): #7      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
I/flutter (15605): #8      SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1029:17)
I/flutter (15605): #9      SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:963:5)
I/flutter (15605): #13     _invoke1 (dart:ui/hooks.dart:265:10)
I/flutter (15605): #14     _beginFrame (dart:ui/hooks.dart:192:3)
I/flutter (15605): (elided 3 frames from dart:async)
I/flutter (15605): This exception was thrown in the context of a scheduler callback. When the scheduler callback was _registered_ (as opposed to when the exception was thrown), this was the stack:
I/flutter (15605): #2      SchedulerBinding.scheduleFrameCallback (package:flutter/src/scheduler/binding.dart:523:49)
I/flutter (15605): #3      FlareRenderBox.paint (package:flare_flutter/flare_render_box.dart:143:37)
I/flutter (15605): #4      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
I/flutter (15605): #5      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
I/flutter (15605): #6      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:131:15)
I/flutter (15605): #7      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
I/flutter (15605): #8      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
I/flutter (15605): #9      RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
I/flutter (15605): #10     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
I/flutter (15605): #11     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
I/flutter (15605): #12     _RenderColoredBox.paint (package:flutter/src/widgets/basic.dart:7318:15)
I/flutter (15605): #13     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
I/flutter (15605): #14     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
I/flutter (15605): #15     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:131:15)
I/flutter (15605): #16     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
I/flutter (15605): #17     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
I/flutter (15605): #18     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:131:15)
I/flutter (15605): #19     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
I/flutter (15605): #20     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:140:11)
I/flutter (15605): #21     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
I/flutter (15605): #22     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:978:29)
I/flutter (15605): #23     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:438:19)
I/flutter (15605): #24     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:914:13)
I/flutter (15605): #25     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:302:5)
I/flutter (15605): #26     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
I/flutter (15605): #27     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
I/flutter (15605): #28     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971:5)
I/flutter (15605): #32     _invoke (dart:ui/hooks.dart:251:10)
I/flutter (15605): #33     _drawFrame (dart:ui/hooks.dart:209:3)
I/flutter (15605): (elided 5 frames from class _FrameCallbackEntry and dart:async)
I/flutter (15605): ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by codenameakshay** [comment]
You actually also need to create Remote Config, to fetch some values. The default ones are present, and remote config can't be fetched was causing the error. Wrapped it up in try block, so that everything works now, with default values, without Remote config.
Create Remote config to change the default values.
