### ISSUE TITLE
Purchase not working

### ISSUE THREAD

**Issue by tasmo** [Hash-Studios/Prism#234]
**Describe the bug**
I cannot purchase the pro version on LineageOS with latest Play Services. When I push the purchase button literally nothing happens. When Yclick again I get an error which says I clicked already and have to wait.

**To Reproduce**
1. Go to 'Buy Premium'
2. Click on 'Purchase'
3. Wait
4. Clich on 'Purchase' again

**Expected behavior**
See any way to purchase.

**Screenshots**
![](https://i.imgur.com/3AqSGDO.png)

**Smartphone (please complete the following information):**
 - Device: Oneplus
 - OS: latest LineageOS 17.1 with latest Play Services
 - Version: 2.6.2

**Comment by LiquidatorCoder** [comment]
@tasmo Were you running the release build or debug?

**Comment by tasmo** [comment]
> @tasmo Were you running the release build or debug?

A release downloaded through Play Store and later the latest release build from here.
